version: '3.7'

services:
  strapi:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/srv/app
    depends_on:
      - mongo
      - caddy
    restart: always
    env_file:
      - ./.env

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    env_file:
      - ./.env
    restart: always
    depends_on:
      - caddy
  caddy:
    image: caddy:alpine
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always




secrets:
  my_secrets:
    file: ./.env
